# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class ErrorResponse(BaseModel):
    status_code: int = Field(..., alias="statusCode", examples=[400])
    """
    HTTP status code.
    """
    code: str = Field(..., examples=["VALIDATION_ERROR"])
    """
    Machine-readable error discriminant. One of: VALIDATION_ERROR,
    AUTH_REQUIRED, TOKEN_EXPIRED, INSUFFICIENT_PERMISSIONS,
    RESOURCE_NOT_FOUND, QUOTA_EXCEEDED, INSUFFICIENT_CREDITS,
    LLM_RATE_LIMITED, LLM_TIMEOUT, LLM_UNAVAILABLE, OCR_FAILED,
    EXTRACTION_FAILED, EXTRACTION_TIMEOUT, FILE_TOO_LARGE,
    DUPLICATE_RESOURCE, DATASPACE_RUN_FAILED, INTERNAL_ERROR.

    """
    error: str = Field(..., examples=["Bad Request"])
    """
    HTTP status name.
    """
    message: str = Field(..., examples=["name is required."])
    """
    Human-readable error description.
    """
    retryable: bool = Field(..., examples=[False])
    """
    Whether the client should retry the request.
    """
    timestamp: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    """
    ISO 8601 timestamp when the error occurred.
    """
    path: str = Field(..., examples=["/v1/schemas"])
    """
    Request path that failed.
    """


class Event(BaseModel):
    event_type: str = Field(..., examples=["document.extracted"])
    """
    The event that triggered this delivery. One of:
    document.extracted, document.extraction_failed,
    run.dataspace.completed, run.dataspace.failed,
    result.dataspace.completed, result.dataspace.failed,
    run.structuring.completed, run.structuring.failed,
    run.resolution.completed, run.resolution.failed,
    run.extraction.completed, run.extraction.failed,
    result.flagged, result.approved, result.rejected,
    delivery.item.completed, delivery.item.failed.

    """
    event_id: str = Field(..., examples=["42"])
    """
    Monotonically increasing event sequence ID.
    """
    binding_id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    """
    The delivery binding that matched this event.
    """
    idempotency_key: str = Field(..., examples=["c9f3a7e1b2d4f6a8e0c2d4f6a8e0c2d4"])
    """
    32-character hex key derived from binding_id + event_id. Stable across retries.
    """
    attempt: int = Field(..., examples=[1])
    """
    Delivery attempt number (1–7).
    """
    delivered_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    """
    Timestamp of this delivery attempt.
    """


class Encoding(Enum):
    utf_8 = "utf-8"
    base64 = "base64"


class Content(BaseModel):
    """
    Binary content envelope (for file-type serializers like CSV/XLSX). Null when payload is used instead.
    """

    mime: str | None = Field(None, examples=["text/csv"])
    encoding: Encoding | None = Field(None, examples=["utf-8"])
    data: str | None = None
    """
    UTF-8 text or base64-encoded binary.
    """


class WebhookEvent(BaseModel):
    """
    Webhook delivery payload sent to configured destinations.
    """

    event: Event
    payload: dict[str, Any] | None = Field(
        None,
        examples=[
            {
                "document_id": "f0e1d2c3-b4a5-9687-8765-432109876543",
                "filename": "invoice-042.pdf",
                "status": "completed",
                "data": {"invoice_number": "INV-2024-0042", "total_amount": 1250},
            }
        ],
    )
    """
    Serialized deliverable data. Shape depends on the deliverable type and serializer format configured on the binding.
    """
    content: Content | None = None
    """
    Binary content envelope (for file-type serializers like CSV/XLSX). Null when payload is used instead.
    """


class Pagination(BaseModel):
    total: int = Field(..., examples=[142])
    """
    Total number of matching records.
    """
    limit: int = Field(..., examples=[20])
    """
    Requested page size.
    """
    has_more: bool = Field(..., examples=[True])
    """
    Whether more pages exist.
    """
    next_cursor: str | None = Field(..., examples=["ZDFhMmIzYzR8MjAyNi0wNC0wM1QxMjowMDowMC4wMDBa"])
    """
    Cursor to pass for the next page. Null if no more pages.
    """


class PaginatedResponse(BaseModel):
    data: list[Any] | None = None
    pagination: Pagination | None = None


class DeletedResponse(BaseModel):
    deleted: bool = Field(..., examples=[True])
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])


class Status(Enum):
    complete = "complete"


class Schema(BaseModel):
    source: str | None = None
    """
    Where the schema came from (e.g. `inline`, `saved`, `auto`).
    """
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    definition: dict[str, Any] | None = None
    save_url: AnyUrl | None = None
    """
    URL to save the auto-generated schema in the dashboard.
    """


class Confidence(BaseModel):
    overall: float | None = Field(None, examples=[0.92], ge=0.0, le=1.0)
    """
    Average confidence across all fields.
    """
    fields: dict[str, float] | None = Field(
        None,
        examples=[{"invoice_number": 0.99, "total_amount": 0.95, "vendor_name": 0.82}],
    )
    """
    Per-field confidence scores.
    """


class Processing(BaseModel):
    duration_ms: int | None = Field(None, examples=[3420])
    """
    Total processing time in milliseconds.
    """
    pages_processed: int | None = Field(None, examples=[3])
    region: str | None = Field(None, examples=["eu-west"])


class Links(BaseModel):
    self: str | None = None
    document: str | None = None
    dashboard: AnyUrl | None = None


class Status1(Enum):
    processing = "processing"


class Status2(Enum):
    queued = "queued"


class Job(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    status: Status2 = Field(..., examples=["completed"])
    poll_url: str = Field(..., examples=["/v1/jobs/abc-123"])
    """
    URL to poll for job progress.
    """
    estimated_seconds: int | None = Field(None, examples=[15])
    """
    Estimated processing time in seconds.
    """


class Document(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    filename: str | None = Field(None, examples=["invoice-042.pdf"])
    pages: int | None = None


class Links1(BaseModel):
    dashboard: AnyUrl | None = None


class ExtractAsyncResponse(BaseModel):
    request_id: UUID = Field(..., examples=["req_x7y8z9a0b1c2d3e4"])
    status: Status1 = Field(..., examples=["completed"])
    job: Job
    document: Document
    links: Links1 | None = None


class ExtractDocumentSummary(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    filename: str | None = Field(None, examples=["invoice-042.pdf"])
    pages: int | None = Field(None, examples=[3])
    size_bytes: int | None = Field(None, examples=[245760])
    type_detected: str | None = Field(None, examples=["Invoice"])
    """
    AI-inferred document type.
    """
    language_detected: str | None = Field(None, examples=["en"])


class Status3(Enum):
    pending = "pending"
    processing = "processing"
    completed = "completed"
    error = "error"


class Source(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    type: str | None = Field(None, examples=["manual"])


class Links2(BaseModel):
    self: str | None = None
    extractions: str | None = None
    dashboard: AnyUrl | None = None


class DocumentResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    filename: str = Field(..., examples=["contract-2024.pdf"])
    pages: int | None = Field(None, examples=[12])
    size_bytes: int | None = Field(None, examples=[1048576])
    mime_type: str | None = Field(None, examples=["application/pdf"])
    type_detected: str | None = Field(None, examples=["Service Contract"])
    language_detected: str | None = Field(None, examples=["en"])
    status: Status3 = Field(..., examples=["completed"])
    source: Source | None = None
    extraction_count: int | None = Field(None, examples=[1])
    latest_extraction_id: UUID | None = Field(
        None, examples=["d1a2b3c4-5678-9abc-def0-1234567890ab"]
    )
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    links: Links2 | None = None


class Status4(Enum):
    complete = "complete"
    failed = "failed"
    processing = "processing"


class Links3(BaseModel):
    self: str | None = None
    document: str | None = None


class ExtractionListItem(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    status: Status4 | None = Field(None, examples=["completed"])
    document_id: UUID | None = Field(None, examples=["f0e1d2c3-b4a5-9687-8765-432109876543"])
    document_filename: str | None = Field(None, examples=["invoice-042.pdf"])
    confidence_overall: float | None = None
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links3 | None = None


class Document1(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    filename: str | None = Field(None, examples=["invoice-042.pdf"])
    pages: int | None = None
    type_detected: str | None = None


class Confidence1(BaseModel):
    overall: float | None = Field(None, ge=0.0, le=1.0)
    fields: dict[str, float] | None = None


class Processing1(BaseModel):
    duration_ms: int | None = None
    pages_processed: int | None = None
    region: str | None = Field(None, examples=["eu-west"])


class Links4(BaseModel):
    self: str | None = None
    data: str | None = None
    document: str | None = None
    dashboard: AnyUrl | None = None


class ExtractionResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    status: Status4 = Field(..., examples=["completed"])
    document: Document1
    data: dict[str, Any]
    """
    Extracted key-value pairs.
    """
    confidence: Confidence1
    locked_fields: list[str] | None = None
    """
    Fields that have been manually corrected (locked at confidence 1.0).
    """
    processing: Processing1 | None = None
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links4 | None = None


class Properties(BaseModel):
    type: str | None = None
    title: str | None = None
    description: str | None = None


class Definition(BaseModel):
    """
    JSON Schema definition of the extraction target.
    """

    type: str | None = Field(None, examples=["object"])
    properties: dict[str, Properties] | None = None
    required: list[str] | None = None


class Links5(Links2):
    pass


class SchemaResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str = Field(..., examples=["Invoice Schema"])
    description: str | None = Field(None, examples=["Standard invoice fields for AP processing."])
    definition: Definition = Field(
        ...,
        examples=[
            {
                "type": "object",
                "properties": {
                    "invoice_number": {"type": "string", "title": "Invoice Number"},
                    "total_amount": {
                        "type": "number",
                        "title": "Total Amount",
                        "description": "Total invoice amount including tax",
                    },
                },
                "required": ["invoice_number"],
            }
        ],
    )
    """
    JSON Schema definition of the extraction target.
    """
    field_count: int | None = Field(None, examples=[8])
    version: int | None = Field(None, examples=[1])
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    updated_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links5 | None = None


class Definition1(BaseModel):
    """
    JSON Schema definition. If provided, `properties` describes the fields.
    Each property key is the field name; the value is an object with `type`,
    optional `title`, and optional `description`.

    """

    properties: dict[str, Properties] | None = None
    required: list[str] | None = None


class FieldModel(BaseModel):
    field_name: str = Field(..., examples=["invoice_number"])
    display_name: str | None = Field(None, examples=["Invoice Number"])
    data_type: str | None = Field(None, examples=["number"])
    """
    Field type hint. Accepted values: string, number, integer, boolean, date, array, object. Defaults to string. Extracted values are returned as the specified type when possible.
    """
    description: str | None = None
    is_required: bool | None = None


class SchemaCreateRequest(BaseModel):
    name: str = Field(..., examples=["Invoice Schema"], max_length=100)
    """
    Schema name.
    """
    description: str | None = None
    """
    Optional description.
    """
    definition: Definition1 | None = None
    """
    JSON Schema definition. If provided, `properties` describes the fields.
    Each property key is the field name; the value is an object with `type`,
    optional `title`, and optional `description`.

    """
    fields: list[FieldModel] | None = None
    """
    Flat fields array (alternative to `definition.properties`). Each element has
    at minimum a `field_name`; other attributes are optional.

    """


class Definition2(BaseModel):
    properties: dict[str, Properties] | None = None
    required: list[str] | None = None


class Field1(BaseModel):
    field_name: str = Field(..., examples=["invoice_number"])
    display_name: str | None = Field(None, examples=["Invoice Number"])
    data_type: str | None = Field(None, examples=["string"])
    description: str | None = None
    is_required: bool | None = None


class SchemaUpdateRequest(BaseModel):
    name: str | None = Field(None, max_length=100)
    description: str | None = None
    definition: Definition2 | None = None
    fields: list[Field1] | None = None
    """
    Flat fields array (alternative to `definition.properties`). Each element has
    at minimum a `field_name`; other attributes are optional.

    """


class Status6(Enum):
    pending = "pending"
    queued = "queued"
    processing = "processing"
    complete = "complete"
    failed = "failed"


class Schema1(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str | None = None


class GridStats(BaseModel):
    """
    Grid fill statistics.
    """

    total_cells: int | None = Field(None, examples=[8850])
    filled: int | None = Field(None, examples=[6200])
    empty: int | None = Field(None, examples=[2650])
    fill_rate: float | None = Field(None, examples=[0.7])


class CurrentPhase(Enum):
    """
    Current pipeline phase.
    """

    phase_1_resolve = "phase_1_resolve"
    phase_2_strategy = "phase_2_strategy"
    phase_2_execute = "phase_2_execute"
    phase_2_outliers = "phase_2_outliers"
    phase_3_validation = "phase_3_validation"
    phase_4_reread = "phase_4_reread"
    completed = "completed"
    error = "error"


class Error(BaseModel):
    """
    Present only when status is `failed`.
    """

    code: str | None = None
    message: str | None = Field(None, examples=["Re-extraction started."])


class Links6(BaseModel):
    self: str | None = None
    cancel: str | None = None
    """
    Cancel URL. Only present for pending/processing jobs.
    """
    dashboard: AnyUrl | None = None


class JobResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str | None = Field(None, examples=["Q1 Invoice Processing"])
    status: Status6 = Field(..., examples=["completed"])
    progress: int | None = Field(None, examples=[45])
    """
    Percentage complete (0–100). Only present while `processing`.
    """
    estimated_seconds_remaining: int | None = None
    schema_: Schema1 | None = Field(None, alias="schema")
    document_count: int | None = Field(None, examples=[150])
    """
    Total documents in the job.
    """
    completed_documents: int | None = Field(None, examples=[67])
    """
    Documents that have finished processing.
    """
    grid_stats: GridStats | None = None
    """
    Grid fill statistics.
    """
    current_phase: CurrentPhase | None = None
    """
    Current pipeline phase.
    """
    error: Error | None = None
    """
    Present only when status is `failed`.
    """
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    started_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    completed_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links6 | None = None


class Status7(Enum):
    active = "active"
    syncing = "syncing"
    error = "error"


class DefaultSchema(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])


class Links7(BaseModel):
    self: str | None = None
    documents: str | None = None
    dashboard: AnyUrl | None = None


class SourceResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str = Field(..., examples=["Invoices Ingest"])
    type: str = Field(..., examples=["api"])
    status: Status7 = Field(..., examples=["completed"])
    document_count: int | None = Field(None, examples=[42])
    default_schema: DefaultSchema | None = None
    endpoint: str | None = Field(None, examples=["/v1/sources/abc-123/documents"])
    """
    URL path for uploading documents to this source.
    """
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links7 | None = None


class SourceCreateRequest(BaseModel):
    name: str = Field(..., examples=["Invoices Ingest"])
    """
    Source name.
    """
    default_schema_id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    """
    Optional schema ID to apply by default to documents in this source.
    """


class SourceUpdateRequest(BaseModel):
    name: str | None = None
    default_schema_id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    """
    Set to null to remove the default schema.
    """


class Status8(Enum):
    """
    `queued` if the document was accepted, `duplicate` if a matching file already exists.
    """

    queued = "queued"
    duplicate = "duplicate"


class Links8(BaseModel):
    document: str | None = None
    source: str | None = None


class IngestDocumentResponse(BaseModel):
    document_id: UUID | None = Field(None, examples=["f0e1d2c3-b4a5-9687-8765-432109876543"])
    """
    ID of the created document (absent if duplicate).
    """
    filename: str | None = Field(None, examples=["invoice-042.pdf"])
    status: Status8 | None = Field(None, examples=["completed"])
    """
    `queued` if the document was accepted, `duplicate` if a matching file already exists.
    """
    source_id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    message: str | None = Field(None, examples=["Re-extraction started."])
    """
    Present when status is `duplicate`.
    """
    existing_document_id: UUID | None = Field(
        None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"]
    )
    """
    Present when status is `duplicate`.
    """
    links: Links8 | None = None


class Links9(BaseModel):
    self: str | None = None


class SourceDocumentItem(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    filename: str | None = Field(None, examples=["invoice-042.pdf"])
    status: Status3 | None = Field(None, examples=["completed"])
    size_bytes: int | None = None
    type_detected: str | None = None
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links9 | None = None


class JobCreateRequest(BaseModel):
    schema_id: UUID = Field(..., examples=["b2c3d4e5-f6a7-8901-bcde-f12345678901"])
    """
    User schema UUID to run this job against.
    """
    document_ids: list[UUID] | None = None
    """
    Optional list of document UUIDs to process. If omitted or empty, all
    completed documents for the authenticated customer are used.

    """
    name: str | None = Field(None, examples=["Q1 Invoice Processing"], max_length=200)
    """
    Optional human-readable job name.
    """


class Status10(Enum):
    """
    The job always starts in `pending` state.
    """

    pending = "pending"


class Links10(BaseModel):
    self: str | None = Field(None, examples=["/v1/jobs/abc-123"])
    results: str | None = Field(None, examples=["/v1/jobs/abc-123/results"])


class JobCreateResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    """
    The newly created job's UUID.
    """
    status: Status10 = Field(..., examples=["completed"])
    """
    The job always starts in `pending` state.
    """
    message: str | None = Field(None, examples=["Job created and queued for processing."])
    links: Links10


class JobStatus(Enum):
    """
    Current job status (with `completed` mapped to `complete`).
    """

    pending = "pending"
    queued = "queued"
    processing = "processing"
    complete = "complete"
    failed = "failed"


class Datum(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    """
    The result row's UUID.
    """
    document_id: UUID | None = Field(None, examples=["f0e1d2c3-b4a5-9687-8765-432109876543"])
    filename: str | None = Field(None, examples=["invoice-042.pdf"])
    status: str | None = Field(None, examples=["completed"])
    """
    Per-row status (e.g. `complete`, `partial`, `failed`).
    """
    values: dict[str, Any] | None = None
    """
    Extracted field values keyed by field name.
    """
    confidence: float | None = None
    """
    Row-level average confidence score.
    """
    validation_flags: list[dict[str, Any]] | None = None
    """
    Validation flags raised during Phase 4.
    """


class Links11(BaseModel):
    self: str | None = None
    job: str | None = None


class JobResultsResponse(BaseModel):
    job_id: UUID = Field(..., examples=["c3d4e5f6-a7b8-9012-cdef-123456789012"])
    job_status: JobStatus
    """
    Current job status (with `completed` mapped to `complete`).
    """
    schema_: Schema1 | None = Field(None, alias="schema")
    total_rows: int = Field(..., examples=[150])
    """
    Number of result rows returned.
    """
    data: list[Datum]
    """
    One entry per processed document.
    """
    links: Links11 | None = None


class Links12(Links9):
    pass


class DialectConfig(BaseModel):
    """
    Dialect configuration payload; all keys optional.
    """

    date_format: str | None = Field(None, examples=["YYYY-MM-DD"])
    """
    Date format pattern (e.g. `YYYY-MM-DD`, `DD/MM/YYYY`).
    """
    number_locale: str | None = Field(None, examples=["en-US"])
    """
    BCP-47 locale tag used for number formatting.
    """
    delimiter: str | None = Field(None, examples=[","])
    """
    CSV column delimiter character.
    """
    null_representation: str | None = Field(None, examples=[""])
    """
    How null values are rendered in serialised output.
    """
    encoding: str | None = Field(None, examples=["UTF-8"])
    """
    Character encoding label (e.g. `UTF-8`, `ISO-8859-1`).
    """
    boolean_format: list[str] | None = Field(
        None, examples=[["true", "false"]], max_length=2, min_length=2
    )
    """
    Exactly 2 strings — `[true_value, false_value]`.
    """


class DialectCreateRequest(BaseModel):
    name: str = Field(..., examples=["European CSV"])
    """
    Dialect name. Required, non-empty.
    """
    date_format: str | None = None
    """
    Date format string (e.g. `YYYY-MM-DD`, `DD/MM/YYYY`).
    """
    number_locale: str | None = None
    """
    BCP-47 locale for number formatting.
    """
    delimiter: str | None = None
    """
    CSV delimiter character.
    """
    null_representation: str | None = None
    """
    Representation of null values.
    """
    encoding: str | None = None
    """
    Character encoding.
    """
    boolean_format: list[str] | None = Field(
        None, examples=[["Yes", "No"]], max_length=2, min_length=2
    )
    """
    Exactly 2 strings — `[true_value, false_value]`.
    """


class DialectUpdateRequest(BaseModel):
    """
    Partial update — only supplied keys are patched.
    """

    name: str | None = None
    date_format: str | None = None
    number_locale: str | None = None
    delimiter: str | None = None
    null_representation: str | None = None
    encoding: str | None = None
    boolean_format: list[str] | None = Field(None, max_length=2, min_length=2)


class MatchType(Enum):
    """
    Matching strategy applied to this pair.
    """

    exact = "exact"
    fuzzy = "fuzzy"
    date_range = "date_range"
    numeric_range = "numeric_range"


class MatchingFieldMapping(BaseModel):
    """
    Field-mapping entry linking an extracted field to a reference-data column.
    The shape below is illustrative — the platform accepts any object shape and
    applies matching using the documented keys when present.

    """

    model_config = ConfigDict(
        extra="allow",
    )
    extracted_field: str | None = Field(None, examples=["vendor_name"])
    """
    Name or id of the extracted field.
    """
    reference_column: str | None = Field(None, examples=["supplier_legal_name"])
    """
    Reference dataset column to match against.
    """
    match_type: MatchType | None = Field(None, examples=["exact"])
    """
    Matching strategy applied to this pair.
    """
    weight: float | None = Field(None, examples=[0.6], ge=0.0)
    """
    Relative weight used to aggregate the final confidence.
    """


class TargetType(Enum):
    run = "run"
    schema = "schema"
    document_filter = "document_filter"


class Links13(BaseModel):
    self: str | None = None
    runs: str | None = None


class MatchingConfigResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str = Field(..., examples=["Supplier lookup"])
    reference_data_id: UUID = Field(..., examples=["b8c9d0e1-f2a3-4567-bcde-678901234567"])
    target_type: TargetType | None = Field(None, examples=["run"])
    target_value: dict[str, Any] | None = None
    """
    Target identifier payload (e.g. run_id, schema_id).
    """
    field_mappings: list[MatchingFieldMapping]
    threshold: float = Field(..., examples=[0.85], ge=0.0, le=1.0)
    """
    Auto-accept confidence threshold.
    """
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    updated_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links13 | None = None


class TargetType1(Enum):
    """
    Target scope type (defaults to `run`).
    """

    run = "run"
    schema = "schema"
    document_filter = "document_filter"


class MatchingConfigCreateRequest(BaseModel):
    name: str
    """
    Human-readable configuration name.
    """
    reference_data_id: UUID = Field(..., examples=["b8c9d0e1-f2a3-4567-bcde-678901234567"])
    """
    UUID of the reference dataset to match against.
    """
    field_mappings: list[MatchingFieldMapping] = Field(..., min_length=1)
    """
    Weighted field-mapping entries. Must be non-empty.
    """
    threshold: float | None = Field(None, ge=0.0, le=1.0)
    """
    Auto-accept confidence threshold (defaults to 0.85 server-side).
    """
    target_type: TargetType1 | None = None
    """
    Target scope type (defaults to `run`).
    """
    target_value: dict[str, Any] | None = None
    """
    Free-form target identifier payload (e.g. `{ run_id }`).
    """


class MatchingConfigUpdateRequest(BaseModel):
    """
    Partial update — only provided keys are applied.
    """

    name: str | None = None
    field_mappings: list[MatchingFieldMapping] | None = Field(None, min_length=1)
    threshold: float | None = Field(None, ge=0.0, le=1.0)
    target_type: TargetType | None = None
    target_value: dict[str, Any] | None = None


class Status11(Enum):
    queued = "queued"
    running = "running"
    completed = "completed"
    failed = "failed"
    cancelled = "cancelled"


class Links14(BaseModel):
    self: str | None = None
    config: str | None = None


class MatchingRunResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    matching_config_id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    status: Status11 = Field(..., examples=["completed"])
    triggered_by: str | None = Field(None, examples=["manual"])
    rows_processed: int | None = None
    rows_matched: int | None = None
    avg_confidence: float | None = None
    started_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    completed_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    error: str | None = None
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links14 | None = None


class MatchResultItem(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    document_id: UUID | None = Field(None, examples=["f0e1d2c3-b4a5-9687-8765-432109876543"])
    document_filename: str | None = None
    matched_reference_row_id: UUID | None = Field(
        None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"]
    )
    confidence: float | None = Field(None, ge=0.0, le=1.0)
    status: str | None = Field(None, examples=["completed"])
    """
    Per-result status (e.g. `auto_accepted`, `needs_review`, `no_match`).
    """
    evidence: dict[str, Any] | None = None
    """
    Per-result evidence payload (top candidates, per-field scores).
    """


class Links15(Links9):
    pass


class RoutingRuleResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str
    trigger_type: str = Field(..., examples=["document_classified"])
    """
    Trigger kind. Always `document_classified` for rules created via this API.
    """
    conditions: dict[str, Any] | None = None
    """
    Mirror of the internal `trigger_config`.
    """
    action_type: str = Field(..., examples=["route_to_schema"])
    """
    Resolved action kind. Defaults to `route_to_schema` when not specified on the request body.
    """
    actions: dict[str, Any] | None = None
    """
    Action payload. May include a `type` key that drives `action_type`.
    """
    priority: int = Field(..., examples=[100])
    """
    Lower runs first. Default 100.
    """
    is_active: bool
    review_required: bool | None = None
    source_connection_id: UUID | None = Field(
        None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"]
    )
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    updated_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links15 | None = None


class Actions(BaseModel):
    """
    Action payload. If an `actions.type` key is provided it becomes the
    rule's `action_type` (default: `route_to_schema`).

    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: str | None = Field(None, examples=["route_to_schema"])
    """
    Action kind identifier.
    """


class RoutingRuleCreateRequest(BaseModel):
    name: str
    """
    Rule name. Required, non-empty.
    """
    conditions: dict[str, Any] | None = None
    """
    Trigger condition payload; stored as `trigger_config` internally.
    """
    actions: Actions | None = None
    """
    Action payload. If an `actions.type` key is provided it becomes the
    rule's `action_type` (default: `route_to_schema`).

    """
    priority: int | None = None
    """
    Lower priority runs first. Defaults to 100 server-side.
    """


class Actions1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str | None = None


class RoutingRuleUpdateRequest(BaseModel):
    """
    Partial update — only supplied keys are patched.
    """

    name: str | None = None
    conditions: dict[str, Any] | None = None
    actions: Actions1 | None = None
    priority: int | None = None
    is_active: bool | None = None


class Destination(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    customer_id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str = Field(..., examples=["Analytics webhook"])
    type: str = Field(..., examples=["webhook"])
    """
    Connector type discriminant — resolves to a registered connector. Live types are `webhook`, `sftp`, `s3`, `azure_blob`, `google_drive`, `onedrive`, `google_sheets`.
    """
    config: dict[str, Any] | None = None
    """
    Connector-specific configuration (e.g. `{ url, headers }` for webhook).
    """
    has_auth_config: bool | None = None
    """
    True when connector credentials are stored for this destination. The credential values themselves are never returned.
    """
    has_signing_secret: bool | None = None
    """
    True when an HMAC signing secret is stored. The secret itself is never returned.
    """
    payload_cap_bytes: int | None = None
    """
    Per-destination override of the TransportWrapper payload cap (bytes).
    """
    is_active: bool
    last_delivery_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    last_delivery_status: str | None = None
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    updated_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])


class CreateDestinationRequest(BaseModel):
    name: str
    type: str
    """
    Connector type. Must match a registered connector. Live types are `webhook`, `sftp`, `s3`, `azure_blob`, `google_drive`, `onedrive`, `google_sheets`.
    """
    config: dict[str, Any] | None = None
    auth_config: dict[str, Any] | None = None
    signing_secret: str | None = None
    payload_cap_bytes: int | None = None
    is_active: bool | None = None


class UpdateDestinationRequest(BaseModel):
    """
    Partial update — every field optional. Only supplied fields are written.
    """

    name: str | None = None
    config: dict[str, Any] | None = None
    auth_config: dict[str, Any] | None = None
    signing_secret: str | None = None
    payload_cap_bytes: int | None = None
    is_active: bool | None = None


class TestConnectionResponse(BaseModel):
    success: bool
    http_status: int | None = Field(None, alias="httpStatus")
    duration_ms: int = Field(..., alias="durationMs")
    message: str | None = None


class SignalFilter(BaseModel):
    """
    Shallow predicate stored on each binding. Slice-1 matching is exact
    event_type + equality on optional `match` keys; richer predicates are
    intentionally out of scope.

    """

    event_type: str = Field(..., examples=["document.extracted"])
    match: dict[str, Any] | None = None
    """
    Optional equality filter on payload keys.
    """


class Rule(BaseModel):
    source: str
    target: str


class FieldMap(BaseModel):
    """
    Declarative projection applied between resolver output and serializer
    input. Operations run in fixed order: drop → rename → static.

    """

    rules: list[Rule] | None = None
    static: dict[str, Any] | None = None
    """
    Literal key/value pairs added last — always wins collisions.
    """
    drop: list[str] | None = None


class RateLimit(BaseModel):
    rate_per_sec: float | None = Field(None, alias="ratePerSec")
    capacity: int | None = None


class DeliveryPolicy(BaseModel):
    """
    Retry / timeout overrides consumed by the TransportWrapper. Slice 1
    defaults to a 6-attempt ladder with backoff `[5s, 30s, 2min, 10min, 1h]`.

    """

    max_attempts: int | None = Field(None, ge=1)
    backoff_schedule: list[int] | None = None
    timeout_ms: int | None = None
    rate_limit: RateLimit | None = None


class DeliveryBinding(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    customer_id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str
    signal_filter: SignalFilter
    deliverable_type: str
    """
    Must resolve to a registered deliverable resolver.
    """
    destination_id: UUID = Field(..., examples=["e1f2a3b4-c5d6-7890-efab-901234567890"])
    field_map: FieldMap | None = None
    serializer_format: str
    """
    Must resolve to a registered serializer (json, ndjson, csv, csv_file, xlsx, rows, graph, raw, md, txt).
    """
    serializer_config: dict[str, Any] | None = None
    delivery_policy: DeliveryPolicy | None = None
    is_active: bool
    last_status: str | None = None
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    updated_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])


class CreateBindingRequest(BaseModel):
    name: str
    signal_filter: SignalFilter
    deliverable_type: str
    destination_id: UUID = Field(..., examples=["e1f2a3b4-c5d6-7890-efab-901234567890"])
    field_map: FieldMap | None = None
    serializer_format: str
    serializer_config: dict[str, Any] | None = None
    delivery_policy: DeliveryPolicy | None = None
    is_active: bool | None = None


class UpdateBindingRequest(BaseModel):
    """
    Partial update — every field optional.
    """

    name: str | None = None
    signal_filter: SignalFilter | None = None
    deliverable_type: str | None = None
    destination_id: UUID | None = Field(None, examples=["e1f2a3b4-c5d6-7890-efab-901234567890"])
    field_map: FieldMap | None = None
    serializer_format: str | None = None
    serializer_config: dict[str, Any] | None = None
    delivery_policy: DeliveryPolicy | None = None
    is_active: bool | None = None


class Status12(Enum):
    in_flight = "in_flight"
    succeeded = "succeeded"
    failed = "failed"


class DeliveryItem(BaseModel):
    """
    One row per delivery attempt.
    """

    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    customer_id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    binding_id: UUID = Field(..., examples=["d0e1f2a3-b4c5-6789-defa-890123456789"])
    event_id: str
    """
    BIGSERIAL id of the originating outbox row (string-encoded).
    """
    idempotency_key: str
    """
    SHA-256-derived key passed on the wire. Stable within an attempt.
    """
    status: Status12 = Field(..., examples=["completed"])
    attempt: int = Field(..., ge=1)
    http_status: int | None = None
    error_code: str | None = None
    error_message: str | None = None
    request_body: str | None = None
    response_body: str | None = None
    duration_ms: int | None = None
    completed_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])


class DeliveryDeadLetter(BaseModel):
    """
    Terminal failure row written after retry exhaustion.
    """

    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    customer_id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    binding_id: UUID = Field(..., examples=["d0e1f2a3-b4c5-6789-defa-890123456789"])
    event_id: str
    """
    BIGSERIAL outbox id (string).
    """
    last_item_id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    """
    FK to the last DeliveryItem attempt (nullable — `ON DELETE SET NULL`).
    """
    error_code: str = Field(..., examples=["delivery_timeout"])
    error_message: str | None = None
    attempts: int
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])


class ProcessingStatus(Enum):
    enqueued = "enqueued"
    no_subscribers = "no-subscribers"
    failed = "failed"


class DeliveryEvent(BaseModel):
    """
    Outbox record (not the typed producer DTO). Represents a single row in
    the `delivery_events` table. `event_type` is a string discriminant —
    see `/v1/delivery/catalog/signals` for the exhaustive list.

    """

    id: str
    """
    BIGSERIAL (string-encoded to avoid JS number precision loss).
    """
    customer_id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    event_type: str
    payload: dict[str, Any]
    """
    Entity IDs only — deliverable resolvers load content at delivery time.
    """
    dedup_key: str | None = None
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    processed_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    processing_attempts: int
    processing_status: ProcessingStatus | None = None
    error: str | None = None


class Kind(Enum):
    record = "record"


class Type(Enum):
    string = "string"
    number = "number"
    boolean = "boolean"
    date = "date"
    datetime = "datetime"
    json = "json"


class Column(BaseModel):
    name: str
    type: Type
    nullable: bool | None = None


class Shape(BaseModel):
    kind: Kind
    is_collection: bool
    columns: list[Column]


class Kind1(Enum):
    blob = "blob"


class Shape1(BaseModel):
    kind: Kind1
    mime: str


class Kind2(Enum):
    graph = "graph"


class Shape2(BaseModel):
    kind: Kind2
    node_types: list[str]
    edge_types: list[str]


class Kind3(Enum):
    envelope = "envelope"


class Shape3(BaseModel):
    kind: Kind3


class DeliverableCatalogEntry(BaseModel):
    type: str
    label: str | None = Field(None, examples=["Customer Onboarding"])
    """
    Short human-readable label, e.g. "Document markdown content". Falls back to `type` if unknown.
    """
    description: str | None = None
    """
    One-line explanation of what the resolver emits.
    """
    compatible_signals: list[str]
    """
    Empty for slice-2 stub resolvers — they appear in the list but never route.
    """
    shape: Shape | Shape1 | Shape2 | Shape3


class Format(Enum):
    """
    Registered serializer format. `csv_file` always emits a complete
    file with header + text/csv mime + .csv filename hint. `md`
    renders record collections as markdown tables, blobs as
    passthrough, envelopes as key/value lists. `txt` is the universal
    fallback and accepts every deliverable shape.

    """

    json = "json"
    ndjson = "ndjson"
    csv = "csv"
    csv_file = "csv_file"
    xlsx = "xlsx"
    rows = "rows"
    graph = "graph"
    raw = "raw"
    md = "md"
    txt = "txt"


class SupportsKind(Enum):
    record = "record"
    blob = "blob"
    graph = "graph"
    envelope = "envelope"


class SerializerCatalogEntry(BaseModel):
    format: Format
    """
    Registered serializer format. `csv_file` always emits a complete
    file with header + text/csv mime + .csv filename hint. `md`
    renders record collections as markdown tables, blobs as
    passthrough, envelopes as key/value lists. `txt` is the universal
    fallback and accepts every deliverable shape.

    """
    supports_kinds: list[SupportsKind]
    """
    Deliverable shape kinds this serializer accepts. Probed against a
    minimal synthetic shape per kind — always reflects the current
    implementation.

    """


class DeliverySemantics(Enum):
    record = "record"
    batch = "batch"
    file = "file"


class DefaultRateLimit(RateLimit):
    pass


class ConnectorCapabilities(BaseModel):
    supported_serializers: list[str]
    supported_deliverable_kinds: list[SupportsKind]
    max_payload_bytes: int | None = None
    """
    Connector's own cap. TransportWrapper enforces the smaller of this and the per-destination override.
    """
    auth_types: list[str]
    delivery_semantics: DeliverySemantics
    default_rate_limit: DefaultRateLimit | None = None


class Available(Enum):
    """
    Always `true`. Present so future gated-preview responses can set `available=false` without breaking consumers.
    """

    boolean_true = True


class SampleMode(Enum):
    """
    `real` — the resolver loaded a synthetic entity and every pipeline
    stage ran. `structural` — the resolver threw (typically
    `entity_missing`) so only the declared shape is returned.

    """

    real = "real"
    structural = "structural"


class Column1(BaseModel):
    name: str | None = None
    type: str | None = None
    nullable: bool | None = None


class Shape4(BaseModel):
    """
    The resolver's declared `DeliverableShape`.
    """

    kind: Kind
    is_collection: bool | None = None
    columns: list[Column1] | None = None


class Shape5(BaseModel):
    """
    The resolver's declared `DeliverableShape`.
    """

    kind: Kind1
    mime: str


class Shape6(BaseModel):
    """
    The resolver's declared `DeliverableShape`.
    """

    kind: Kind2
    node_types: list[str] | None = None
    edge_types: list[str] | None = None


class Shape7(BaseModel):
    """
    The resolver's declared `DeliverableShape`.
    """

    kind: Kind3


class Resolver(BaseModel):
    type: str
    """
    Registered deliverable-resolver type (e.g. `markdown`, `run.dataspace.outcome`).
    """
    shape: Shape4 | Shape5 | Shape6 | Shape7
    """
    The resolver's declared `DeliverableShape`.
    """


class WirePreview(BaseModel):
    """
    Static projection of how the wire-level payload would look at delivery time. Never sent to the connector. `null` when `sample_mode="structural"`.
    """

    body_preview: str
    """
    UTF-8 body stringification, truncated to the first 8 KiB with an ellipsis if longer.
    """
    mime: str | None = None
    """
    Inferred content type of the body.
    """
    size_bytes: int
    """
    Full body size in bytes (the serializer's real output, not the truncated preview).
    """
    headers_preview: dict[str, str]
    """
    The `X-Talonic-*` headers that would ship on the wire. The
    `X-Talonic-Signature` header, when present, is rendered as
    `t=<preview>,v1=<preview>` — the preview never computes a real
    HMAC so the signing secret is not exercised.

    """


class StructuralSample(BaseModel):
    """
    Only present when `sample_mode="structural"`. Mirrors `resolver.shape` for convenience.
    """

    deliverable_type: str | None = None
    shape: Any | None = None
    """
    Same `DeliverableShape` union as `resolver.shape`.
    """


class BindingPreviewResponse(BaseModel):
    """
    Output of `POST /v1/delivery/bindings/{id}/preview`. When the resolver
    successfully loads a synthetic entity the full pipeline (`resolve →
    projectFieldMap → serialize`) runs and `sample_mode="real"`. When the
    resolver throws (commonly `EntityMissingError` on a synthetic id) the
    service falls back to `sample_mode="structural"` and returns only the
    resolver's declared shape — `projected`, `serialized`, and
    `wire_preview` are `null` in that case.

    """

    available: Available
    """
    Always `true`. Present so future gated-preview responses can set `available=false` without breaking consumers.
    """
    sample_mode: SampleMode
    """
    `real` — the resolver loaded a synthetic entity and every pipeline
    stage ran. `structural` — the resolver threw (typically
    `entity_missing`) so only the declared shape is returned.

    """
    signal: dict[str, Any]
    """
    Synthetic {DeliveryEvent} built from `signal_filter.event_type`
    with placeholder entity ids (`<preview-{field}>`) and
    `signal_filter.match` overlaid so the synthetic signal passes its
    own filter. `customer_id` always matches the authenticated tenant.

    """
    resolver: Resolver
    projected: dict[str, Any] | None
    """
    Resolver output after `projectFieldMap(binding.field_map)`. `null` when `sample_mode='structural'`.
    """
    serialized: dict[str, Any] | None
    """
    Serializer output (`kind: 'bytes' | 'rows' | 'graph' | 'object'` + per-kind fields). `null` when `sample_mode='structural'`.
    """
    wire_preview: WirePreview | None
    """
    Static projection of how the wire-level payload would look at delivery time. Never sent to the connector. `null` when `sample_mode="structural"`.
    """
    structural_sample: StructuralSample | None = None
    """
    Only present when `sample_mode="structural"`. Mirrors `resolver.shape` for convenience.
    """
    fallback_reason: str | None = None
    """
    Only present when `sample_mode="structural"`. Human-readable reason the resolver could not produce a real sample.
    """


class FilenameTemplateDescription(RootModel[str]):
    root: str
    """
    Tokens replaced inside filename / object-key templates:
    `{binding_id}`, `{event_id}`, `{customer_id}`, `{idempotency_key}`,
    `{attempt}`, `{timestamp_iso}`, `{date}` (UTC YYYY-MM-DD), and
    `{deliverable_type}`. Unknown tokens pass through verbatim so typos
    surface on first delivery. Path-traversal segments (`..`) are stripped.
    See `packages/api/src/delivery/connectors/common/filename-template.ts`.

    """


class SftpDestinationConfig(BaseModel):
    """
    Destination `config` shape when `type="sftp"`. Pairs with an
    `auth_config` of type `password` or `private_key`.

    """

    host: str
    """
    SFTP server hostname.
    """
    port: int | None = 22
    """
    SSH port. Default 22.
    """
    username: str
    remote_path: str
    """
    Absolute remote directory that uploads land in.
    """
    filename_template: str | None = "delivery_{event_id}"
    """
    Optional filename template. Default `delivery_{event_id}`. See
    `FilenameTemplateDescription`. If the rendered filename already
    ends with an extension the operator value wins; otherwise the
    payload's derived extension is appended.

    """
    timeout_ms: int | None = 30000
    """
    Connect / operation timeout in milliseconds.
    """


class S3DestinationConfig(BaseModel):
    """
    Destination `config` shape when `type="s3"`. Pairs with an
    `auth_config` of type `access_key`.

    """

    bucket: str
    region: str
    """
    AWS region, e.g. `us-east-1`.
    """
    key_template: str | None = "delivery/{date}/{event_id}"
    """
    Optional S3 key template. Default `delivery/{date}/{event_id}`.
    See `FilenameTemplateDescription`. Leading slashes are trimmed;
    an extension is appended if the template does not already end in
    one.

    """
    public_read: bool | None = None
    """
    When true, sets `ACL=public-read` on the upload.
    """


class AzureBlobDestinationConfig(BaseModel):
    """
    Destination `config` shape when `type="azure_blob"`. Pairs with an
    `auth_config` of type `connection_string` or `account_key`. With
    `account_key` the public `https://{account_name}.blob.core.windows.net`
    URL is built from `account_name`.

    """

    account_name: str
    container: str
    blob_key_template: str | None = "delivery/{date}/{event_id}"
    """
    Optional blob-key template. Default `delivery/{date}/{event_id}`.
    See `FilenameTemplateDescription`. Leading slashes are trimmed;
    an extension is appended if the template does not already end in
    one.

    """


class Type1(Enum):
    password = "password"


class AuthConfigPassword(BaseModel):
    """
    SFTP password auth.
    """

    type: Literal["password"]
    password: str


class Type2(Enum):
    private_key = "private_key"


class AuthConfigPrivateKey(BaseModel):
    """
    SFTP key-based auth. `passphrase` is optional.
    """

    type: Literal["private_key"]
    private_key: str
    passphrase: str | None = None


class Type3(Enum):
    access_key = "access_key"


class AuthConfigAccessKey(BaseModel):
    """
    S3 IAM access-key pair. `session_token` is optional (STS).
    """

    type: Literal["access_key"]
    access_key_id: str
    secret_access_key: str
    session_token: str | None = None


class Type4(Enum):
    connection_string = "connection_string"


class AuthConfigConnectionString(BaseModel):
    """
    Azure Blob Storage connection string auth.
    """

    type: Literal["connection_string"]
    connection_string: str


class Type5(Enum):
    account_key = "account_key"


class AuthConfigAccountKey(BaseModel):
    """
    Azure Blob Storage shared-key auth (`account_name` lives in the destination `config`).
    """

    type: Literal["account_key"]
    account_key: str


class Type6(Enum):
    bearer = "bearer"


class AuthConfigBearer(BaseModel):
    """
    Webhook Bearer-token auth. Emits `Authorization: Bearer {token}`.
    """

    type: Literal["bearer"]
    token: str


class Type7(Enum):
    basic = "basic"


class AuthConfigBasic(BaseModel):
    """
    Webhook HTTP Basic auth. Emits `Authorization: Basic base64(username:password)`.
    """

    type: Literal["basic"]
    username: str | None = None
    password: str | None = None


class Type8(Enum):
    api_key = "api_key"


class AuthConfigApiKey(BaseModel):
    """
    Webhook API-key auth. Header name defaults to `X-API-Key`.
    """

    type: Literal["api_key"]
    api_key: str
    header_name: str | None = "X-API-Key"


class Type9(Enum):
    none = "none"


class AuthConfigNone(BaseModel):
    """
    Explicit "no authentication" marker.
    """

    type: Literal["none"]


class FilterCondition(BaseModel):
    field_id: str = Field(..., alias="fieldId", examples=["amount"])
    """
    User-schema field id or materialised column identifier.
    """
    operator: str = Field(..., examples=["between"])
    """
    Operator identifier (free-form — e.g. `eq`, `contains`, `between`).
    """
    value: Any | None = None
    """
    Primary value. Shape depends on the operator.
    """
    value_to: Any | None = Field(None, alias="valueTo")
    """
    Upper bound for range operators such as `between`.
    """


class Direction(Enum):
    """
    Sort direction.
    """

    asc = "asc"
    desc = "desc"


class FilterSort(BaseModel):
    field_id: str = Field(..., alias="fieldId")
    """
    Field id to sort by.
    """
    direction: Direction
    """
    Sort direction.
    """


class FilterDocumentsRequest(BaseModel):
    source_id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    """
    Optional source connection UUID to narrow the result set.
    """
    conditions: list[FilterCondition] | None = None
    """
    Ordered list of filter conditions, ANDed together.
    """
    search: str | None = None
    """
    Optional free-text search applied alongside the structured conditions.
    """
    sort: FilterSort | None = None
    page: int | None = Field(None, ge=1)
    """
    1-based page number. Default 1.
    """
    limit: int | None = Field(None, ge=1)
    """
    Page size. Server clamps to a maximum of 500. Default 50.
    """


class FilterDocumentsResponse(BaseModel):
    data: list[dict[str, Any]]
    """
    Matching document rows.
    """
    total: int = Field(..., examples=[142])
    """
    Total number of matching documents.
    """
    links: Links15 | None = None


class SearchResponse(BaseModel):
    """
    Multi-collection search result. Empty arrays are returned for any
    collection with no matches; empty queries return all empty arrays.

    """

    documents: list[dict[str, Any]] | None = None
    field_matches: list[dict[str, Any]] | None = Field(None, alias="fieldMatches")
    sources: list[dict[str, Any]] | None = None
    schemas: list[dict[str, Any]] | None = None
    fields: list[dict[str, Any]] | None = None


class Links17(BaseModel):
    self: str | None = None
    action: str | None = None


class ReviewRecordItem(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    run_id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    document_id: UUID | None = Field(None, examples=["f0e1d2c3-b4a5-9687-8765-432109876543"])
    schema_id: UUID | None = Field(None, examples=["b2c3d4e5-f6a7-8901-bcde-f12345678901"])
    status: str = Field(..., examples=["completed"])
    """
    Review status (e.g. `pending`, `approved`, `rejected`).
    """
    overall_confidence: float | None = Field(None, ge=0.0, le=1.0)
    assigned_to: str | None = None
    reviewed_by: str | None = None
    reviewed_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links17 | None = None


class ReviewRecordDetail(ReviewRecordItem):
    field_decisions: dict[str, Any] | None = None
    """
    Per-field decisions persisted on the record.
    """
    low_confidence_fields: list[str] | None = None
    """
    Names of fields that fell below the review confidence threshold.
    """
    review_comment: str | None = None


class Action(Enum):
    """
    Decision applied to the record.
    """

    approve = "approve"
    reject = "reject"


class ReviewActionRequest(BaseModel):
    action: Action
    """
    Decision applied to the record.
    """
    reason: str | None = None
    """
    Optional reviewer note stored on the record.
    """


class Action1(Enum):
    """
    Decision applied to every record in `ids`.
    """

    approve = "approve"
    reject = "reject"


class ReviewBatchActionRequest(BaseModel):
    ids: list[UUID] = Field(..., min_length=1)
    """
    Non-empty list of validation-record UUIDs.
    """
    action: Action1
    """
    Decision applied to every record in `ids`.
    """


class Result(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    status: str = Field(..., examples=["completed"])
    """
    Per-record outcome (`approved`, `rejected`, or `error`).
    """
    error: str | None = None
    """
    Present on `status: error` rows (e.g. `not_found`).
    """


class ReviewBatchActionResponse(BaseModel):
    processed: int
    """
    Number of records successfully updated.
    """
    failed: int
    """
    Number of records that could not be updated (not found, not owned).
    """
    results: list[Result]


class Links18(Links9):
    pass


class GroundTruthDatasetResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str
    description: str | None = None
    user_schema_id: UUID | None = Field(None, examples=["b2c3d4e5-f6a7-8901-bcde-f12345678901"])
    document_count: int | None = None
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links18 | None = None


class GroundTruthDatasetCreateRequest(BaseModel):
    name: str
    """
    Dataset name. Required, non-empty.
    """
    description: str | None = None
    """
    Optional free-text description.
    """


class GroundTruthEntryItem(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    document_id: UUID | None = Field(None, examples=["f0e1d2c3-b4a5-9687-8765-432109876543"])
    expected_data: dict[str, Any] | None = None
    """
    The known-correct field values for this document.
    """
    notes: str | None = None
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])


class Links19(BaseModel):
    self: str | None = None
    results: str | None = None


class BenchmarkResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str | None = None
    dataset_id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    user_schema_id: UUID | None = Field(None, examples=["b2c3d4e5-f6a7-8901-bcde-f12345678901"])
    status: str = Field(..., examples=["completed"])
    """
    Benchmark run status.
    """
    accuracy_overall: float | None = Field(None, ge=0.0, le=1.0)
    accuracy_by_field: dict[str, Any] | None = None
    documents_processed: int | None = None
    documents_total: int | None = None
    duration_ms: int | None = None
    accuracy_delta: float | None = None
    """
    Change in overall accuracy vs the compared run.
    """
    compared_to_run_id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    completed_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links19 | None = None


class BenchmarkResultItem(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    document_id: UUID | None = Field(None, examples=["f0e1d2c3-b4a5-9687-8765-432109876543"])
    ground_truth_entry_id: UUID | None = Field(
        None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"]
    )
    accuracy: float | None = Field(None, ge=0.0, le=1.0)
    field_results: dict[str, Any] | None = None
    """
    Per-field pass/fail results for this document.
    """
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])


class Status13(Enum):
    accumulating = "accumulating"
    submitted = "submitted"
    in_progress = "in_progress"
    completed = "completed"
    failed = "failed"
    expired = "expired"


class Provider(Enum):
    anthropic = "anthropic"
    bedrock = "bedrock"


class Links20(Links9):
    pass


class BatchResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    status: Status13 = Field(..., examples=["completed"])
    provider: Provider = Field(..., examples=["anthropic"])
    item_count: int
    succeeded_count: int
    errored_count: int
    expired_count: int
    submitted_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    completed_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    error_message: str | None = None
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    updated_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links20


class Item(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    document_id: UUID = Field(..., examples=["f0e1d2c3-b4a5-9687-8765-432109876543"])
    document_filename: str | None = None
    custom_id: str | None = None
    status: str = Field(..., examples=["completed"])
    error_message: str | None = None
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    processed_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])


class BatchDetailResponse(BatchResponse):
    items: list[Item] | None = None


class CaseListItem(BaseModel):
    id: str
    """
    Case key (same value as `case_key`).
    """
    case_key: str = Field(..., examples=["7a3f2b1c"], pattern="^[a-fA-F0-9]{8,64}$")
    label: str | None
    document_count: int
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links20


class Document2(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    filename: str | None = Field(None, examples=["invoice-042.pdf"])
    document_type: str | None = None
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])


class Links22(BaseModel):
    self: str | None = None
    documents: str | None = None


class CaseDetailResponse(BaseModel):
    id: str
    case_key: str = Field(..., examples=["7a3f2b1c"])
    label: str | None = None
    narrative: str | None = None
    documents: list[Document2]
    anomaly_count: int
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links22


class Links23(Links9):
    pass


class DocumentTypeResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str
    ontology_type_id: str | None = None
    category_id: str | None = None
    document_count: int
    links: Links23


class Links24(BaseModel):
    self: str | None = None
    similar: str | None = None


class FieldResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    canonical_name: str = Field(..., examples=["invoice_number"])
    display_name: str | None = None
    data_type: str = Field(..., examples=["string"])
    tier: int
    cluster_name: str | None = None
    occurrence_count: int
    master_instruction: str | None = None
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    updated_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links24


class RecentOccurrence(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    document_id: UUID | None = Field(None, examples=["f0e1d2c3-b4a5-9687-8765-432109876543"])
    document_filename: str | None = None
    raw_field_name: str | None = None
    value: Any | None = None
    """
    Raw extracted value for this occurrence.
    """
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])


class FieldDetailResponse(FieldResponse):
    recent_occurrences: list[RecentOccurrence] | None = Field(None, max_length=20)


class Links25(Links9):
    pass


class FieldHarmonizationItem(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    canonical_name: str = Field(..., examples=["invoice_number"])
    display_name: str | None = None
    data_type: str = Field(..., examples=["string"])
    tier: int
    occurrence_count: int
    schema_count: int
    document_type_names: list[str | None] | None = None
    is_universal: bool
    links: Links25


class Links26(BaseModel):
    self: str | None = None
    rows: str | None = None


class ReferenceDataResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str
    source_type: str
    """
    e.g. `csv`, `xlsx`.
    """
    row_count: int
    columns: Any
    """
    Column schema for the dataset. Shape follows the uploaded file's header row.
    """
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    links: Links26


class Period(BaseModel):
    from_: AwareDatetime = Field(..., alias="from", examples=["2026-04-25T14:30:00.000Z"])
    to: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])


class Totals(BaseModel):
    input_tokens: int
    output_tokens: int
    calls: int


class BreakdownItem(BaseModel):
    operation_type: str
    model: str
    input_tokens: int
    output_tokens: int
    calls: int


class Links27(Links9):
    pass


class UsageResponse(BaseModel):
    period: Period
    totals: Totals
    breakdown: list[BreakdownItem]
    links: Links27


class Totals1(BaseModel):
    input_tokens: int
    output_tokens: int
    cost_estimate_usd: float
    calls: int


class Entry(BaseModel):
    id: str
    operation_type: str
    model: str
    input_tokens: int
    output_tokens: int
    cache_read_tokens: int | None = None
    cost_estimate_usd: float | None = None
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])


class Links28(Links3):
    pass


class DocumentUsageResponse(BaseModel):
    document_id: UUID = Field(..., examples=["f0e1d2c3-b4a5-9687-8765-432109876543"])
    totals: Totals1
    entries: list[Entry]
    links: Links28


class Status14(Enum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"


class Links29(Links19):
    pass


class ResolutionResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    source_run_id: UUID | None = Field(None, examples=["f2a3b4c5-d6e7-8901-fabc-012345678901"])
    status: Status14 = Field(..., examples=["completed"])
    documents_processed: int | None = None
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    completed_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links29


class Category(Enum):
    identity = "identity"
    transaction = "transaction"
    reference = "reference"


class LinkKeyResponse(BaseModel):
    field_name: str = Field(..., examples=["invoice_number"])
    category: Category = Field(..., examples=["identity"])
    auto_classified: bool | None = None
    frequency: float | None = None
    """
    Fraction of documents containing this link key value.
    """


class Links30(BaseModel):
    self: str | None = None
    versions: str | None = None


class SchemaGraphClassResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str
    description: str | None = None
    version: int
    field_count: int
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    updated_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links30


class Status15(Enum):
    pending = "pending"
    approved = "approved"
    rejected = "rejected"


class SchemaGraphDiffResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    class_id: UUID = Field(..., examples=["a7b8c9d0-e1f2-3456-abcd-567890123456"])
    from_version: int | None = None
    to_version: int | None = None
    status: Status15 = Field(..., examples=["completed"])
    changes: list[dict[str, Any]] | None = None
    """
    List of field additions, removals, and modifications.
    """
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    decided_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])


class StructuringCheckResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str
    description: str | None = None
    type: str
    """
    Check type: field_format, value_range, cross_field, ai_coherence.
    """
    config: dict[str, Any] | None = None
    enabled: bool | None = None
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    updated_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])


class StructuringCheckCreateRequest(BaseModel):
    name: str
    description: str | None = None
    type: str
    """
    Check type: field_format, value_range, cross_field, ai_coherence.
    """
    config: dict[str, Any] | None = None
    enabled: bool | None = True


class Rule1(BaseModel):
    id: UUID | None = Field(None, examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    type: str | None = None
    threshold: float | None = None


class StructuringGateResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str
    description: str | None = None
    schema_id: UUID | None = Field(None, examples=["b2c3d4e5-f6a7-8901-bcde-f12345678901"])
    rules: list[Rule1]
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    updated_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])


class StructuringGateCreateRequest(BaseModel):
    name: str
    description: str | None = None
    schema_id: UUID | None = Field(None, examples=["b2c3d4e5-f6a7-8901-bcde-f12345678901"])


class Links31(Links9):
    pass


class GoldenSampleResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str
    description: str | None = None
    sample_count: int | None = None
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    links: Links31 | None = None


class Links32(Links19):
    pass


class ValidationRunResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    golden_sample_id: UUID | None = Field(None, examples=["e5f6a7b8-c9d0-1234-efab-345678901234"])
    schema_id: UUID | None = Field(None, examples=["b2c3d4e5-f6a7-8901-bcde-f12345678901"])
    status: Status14 = Field(..., examples=["completed"])
    accuracy_overall: float | None = None
    documents_processed: int | None = None
    created_at: AwareDatetime = Field(..., examples=["2026-04-25T14:30:00.000Z"])
    completed_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links32 | None = None


class ExtractSyncResponse(BaseModel):
    extraction_id: UUID = Field(..., examples=["d1a2b3c4-5678-9abc-def0-1234567890ab"])
    request_id: str = Field(..., examples=["req_x7y8z9a0b1c2d3e4"])
    status: Status = Field(..., examples=["complete"])
    document: ExtractDocumentSummary
    data: dict[str, Any] = Field(
        ...,
        examples=[
            {
                "invoice_number": "INV-2024-0042",
                "total_amount": 1250,
                "vendor_name": "Acme Corp",
            }
        ],
    )
    """
    Extracted key-value pairs.
    """
    schema_: Schema | None = Field(None, alias="schema")
    confidence: Confidence | None = None
    processing: Processing | None = None
    links: Links | None = None


class DialectResponse(BaseModel):
    id: UUID = Field(..., examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])
    name: str = Field(..., examples=["European CSV"])
    version: int | None = Field(None, examples=[1])
    """
    Monotonically increasing version counter. Bumped on every update.
    """
    config: DialectConfig | None = None
    created_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    updated_at: AwareDatetime | None = Field(None, examples=["2026-04-25T14:30:00.000Z"])
    links: Links12 | None = None


class MatchingRunDetailResponse(MatchingRunResponse):
    results: list[MatchResultItem] | None = None
    """
    Up to the 50 highest-confidence match results.
    """


class DestinationAuthConfig(
    RootModel[
        AuthConfigPassword
        | AuthConfigPrivateKey
        | AuthConfigAccessKey
        | AuthConfigConnectionString
        | AuthConfigAccountKey
        | AuthConfigBearer
        | AuthConfigBasic
        | AuthConfigApiKey
        | AuthConfigNone
    ]
):
    root: (
        AuthConfigPassword
        | AuthConfigPrivateKey
        | AuthConfigAccessKey
        | AuthConfigConnectionString
        | AuthConfigAccountKey
        | AuthConfigBearer
        | AuthConfigBasic
        | AuthConfigApiKey
        | AuthConfigNone
    ) = Field(..., discriminator="type")
    """
    Destination credential payload. Write-only — server responses expose
    only `has_auth_config: boolean`, never the credential values
    themselves. The `type` field discriminates the concrete shape; valid
    values depend on the parent destination's connector `type` (see
    `/v1/delivery/catalog/connectors` for each connector's `auth_types`).

    """


class GroundTruthDatasetDetailResponse(GroundTruthDatasetResponse):
    samples: list[GroundTruthEntryItem] | None = None


class BenchmarkDetailResponse(BenchmarkResponse):
    results: list[BenchmarkResultItem] | None = None
